### PR TITLE
Change image loading

### PR DESCRIPTION
**Pull request by hcorson-dosch**
This updates how the diagram is toggled between the English and Spanish versions. Previously, the src for the image was reset when the button was pressed, but this resulted in a really slow first load for the Spanish version. Now, both images are loaded on page load, but `v-show` is used to set which is shown, defaulting to hiding the Spanish diagram. I think this may slow down initial page load, but the user can _see_ the diagram loading during that time, so at least knows what is happening. Before, when toggling to Spanish, there was no indication that the Spanish version was loading, there was just a considerable delay.

### CODE REVIEW

**Review by ceenell — CHANGES_REQUESTED** [review]
I think the extra page load time is concerning. If it is slow when switching to the Spanish version, now it should be 2x as slow because it is loading both on first draw. You should add lazy loading to the Spanish one so it loads and sits in the background only after the English has loaded. 

This could also slow down zooming and panning the diagram if there are two large files open. 

Another option is to set the page up so the background is embedded as an image, and there's just one, and the text elements are svg on top. That way only the svg would change which should be much faster.

**Comment by hcorson-dosch** [comment]
> I think the extra page load time is concerning. If it is slow when switching to the Spanish version, now it should be 2x as slow because it is loading both on first draw. You should add lazy loading to the Spanish one so it loads and sits in the background only after the English has loaded.

I'll look into lazy loading to speed up the initial page load, but to clarify what I meant -- On the current prod site, when you click to change to Spanish it takes 15+ seconds (with no visual feedback) to load Spanish. With this change, the initial page load of the English version, where the image slowly loads from top to bottom, does take about 10 seconds longer (because both images are being loaded), but the switch to the Spanish version is very fast (~ 1 second). Obviously that longer page load is not good either, so I agree it would be worth trying to reduce it.

> This could also slow down zooming and panning the diagram if there are two large files open.

Agreed - I'm not sure how that would be handled currently. It doesn't _seem_ too different in the local preview.

> Another option is to set the page up so the background is embedded as an image, and there's just one, and the text elements are svg on top. That way only the svg would change which should be much faster.

Do you want me to look into that? We'd previously put any svg exploration on hold.

**Comment by ceenell** [comment]
I think the overall slower load time is more problematic than a slow Spanish time, because if a user doesn't see the diagram and leaves the page, they'll have no opportunity to press the button. I'd like for you to either sort out the lazy loading OR use the svg text before merging to try to mitigate slow loading. With throttling I'm getting longer load times on this version than 10 secs

**Comment by hcorson-dosch** [comment]
> I think the overall slower load time is more problematic than a slow Spanish time, because if a user doesn't see the diagram and leaves the page, they'll have no opportunity to press the button. I'd like for you to either sort out the lazy loading OR use the svg text before merging to try to mitigate slow loading. With throttling I'm getting longer load times on this version than 10 secs

Ok - a 3rd option would be to just delete this PR and stick with the current approach, if this tradeoff isn't worth it.

**Comment by ceenell** [comment]
You're on the right track, let's see this through

**Review by ceenell — DISMISSED** [review]

**Comment by hcorson-dosch** [comment]
Okay I decided the easiest approach was to take advantage of the existing `onImageLoad()` function. I've added in `v-if` statements to each of the picture elements, so that the English diagram is renders on initial page load and the Spanish version does not. As soon as the English diagram image has loaded, it triggers the `onImageLoad()` function, which now updates the variable controlling the `v-if` on the Spanish picture element, triggering the load of that image. If you watch the console (after clearing your browser cache), you'll see that the console statement notes that the English diagram is loaded and then after a delay of about 6 seconds (on my computer) it notes that the Spanish diagram has loaded. You can also see the staggered loading in the Network tab of the inspector.

If someone comes to the page and clicks the 'cambiar a español' button _before_ the English diagram has loaded, they do have to wait for the English image to load (though it is not shown) before the Spanish image will load.

**Review by ceenell — APPROVED** [review]
Ok great, this looks like a good solution.

**Review by ceenell — APPROVED** [review]

**Pull request merged**
